---
title: "Báo cáo doanh số theo nhà thuốc"
author: "Real-time Analytics"
date: "`r format(Sys.time(), '%d-%m-%Y %H:%M')`"
runtime: shiny
output:
    flexdashboard::flex_dashboard:
        theme: flatly
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, comment = "", message = FALSE, warning = FALSE)
Sys.setlocale(category='LC_ALL','en_US.UTF-8')
options(shiny.sanitize.errors = FALSE, scipen = 999) # large numbers should be in full display
sys_user <- Sys.info()["user"]

```


```{r helper-functions, include=FALSE}

table <- function(..., useNA = 'ifany') base::table(..., useNA = useNA)

```


```{r import-data, include=FALSE}

## -----------------------------------------------------------------------------
## load packages

pkgs <- c("readr", "tidyr", "dplyr", "shiny", "xlsx", "RTA")
sapply(pkgs, require, character.only = TRUE)

switch(
    sys_user,
    anchu = {library("DT")},
    {library("DT", lib.loc = "/home/haoly/R/library/DT-1.0.0")}
)

## -----------------------------------------------------------------------------
## import data

switch(
    sys_user,
    anchu = {
        data_dir <- "~/rtanalytics-svnrepo/4.Analytics_South/1.Projects/2.Enterprises/1.DGW/Kingsmen/data/"
        try(msr_sales <- read_csv(paste0(data_dir, "MSR_SALES/MSR_SALES_DEMO.csv"), col_types = cols(.default = "c")))
        try(msr_sales_re <- read_csv(paste0(data_dir, "MSR_SALES/sales_rr.csv"), col_types = cols(.default = "c")))
        try(msr_remote_sales <- read_csv(paste0(data_dir, "MSR_REMOTE_SALES/MSR_SALES_REMOTE_DEMO.csv"), col_types = cols(.default = "c")))
        try(msr_remote_sales_re <- read_csv(paste0(data_dir, "MSR_REMOTE_SALES/sales_rr.csv"), col_types = cols(.default = "c")))
        try(msr_inventory <- read_csv(paste0(data_dir, "MSR_INVENTORY/MSR_INVENTORY_DEMO.csv"), col_types = cols(.default = "c")))
        try(msr_inventory_re <- read_csv(paste0(data_dir, "MSR_INVENTORY/sales_rr.csv"), col_types = cols(.default = "c")))

        try(msr_product <- get_dm_data("C011", "MSR_product"))
        try(msr_store <- get_dm_data("C011", "MSR_store"))
        try(msr_staff <- get_dm_data("C011", "MSR_staff"))
        colnames_dict <- get_dm_data("C011", "colnames_dict")
    }, {
        try(msr_sales <- get_family_data("C011", "MSR_SALES_DEMO"))
        try(msr_sales_re <- get_family_data("C011", "MSR_SALES_DEMO", "sales_rr"))
        try(msr_remote_sales <- get_family_data("C011", "MSR_SALES_REMOTE_DEMO"))
        try(msr_remote_sales_re <- get_family_data("C011", "MSR_SALES_REMOTE_DEMO", "sales_rr"))
        try(msr_inventory <- get_family_data("C011", "MSR_INVENTORY_DEMO"))
        try(msr_inventory_re <- get_family_data("C011", "MSR_INVENTORY_DEMO","sales_rr"))

        try(msr_product <- get_dm_data("C011", "MSR_product"))
        try(msr_store <- get_dm_data("C011", "MSR_store"))
        try(msr_staff <- get_dm_data("C011", "MSR_staff"))
        colnames_dict <- get_dm_data("C011", "colnames_dict")
    }
)

```

```{r, include=FALSE}

gen_ymd <- function(x, by = c("submission_date", "starttime")) {
    by <- match.arg(by)
    if (!any(names(x) == by)) {
        stop(sprintf("column '%s' can not be found", by), call. = FALSE)
    }
    x[[by]] <- as.POSIXct(x[[by]])
    x$year <- lubridate::year(x[[by]])
    x$month <- lubridate::month(x[[by]])
    x$date <- lubridate::date(x[[by]])
    x
}

```

```{r, include=FALSE}

## -----------------------------------------------------------------------------
##

msr_sales_re <- left_join(msr_sales_re, msr_sales, by = "instanceID")
msr_sales_re <- replace_with_na(msr_sales_re)

msr_remote_sales_re <- left_join(msr_remote_sales_re, msr_sales, by = "instanceID")
msr_remote_sales_re <- replace_with_na(msr_remote_sales_re)

msr_inventory_re <- left_join(msr_inventory_re, msr_inventory, by = "instanceID")
msr_inventory_re <- replace_with_na(msr_inventory_re)

region_dict <- msr_store %>% filter(!duplicated(region_id))
region_dict <- make_dict(region_dict$region_id, region_dict$region_lb)

colnames_dict <- make_dict(colnames_dict$col_id, colnames_dict$col_lb)

## remove testing instances
msr_staff <- filter(msr_staff, username != "dgw_vthieu")
msr_staff <- filter(msr_staff, grepl("^dgw", username))

msr_sales_re <- filter(msr_sales_re, grepl("^dgw", username))
msr_remote_sales_re <- filter(msr_remote_sales_re, grepl("^dgw", username))
msr_inventory_re <- filter(msr_inventory_re, grepl("^dgw", username))

## -----------------------------------------------------------------------------
##

## direct sales
msr_sales_re <- select(msr_sales_re,
                       submission_date, staff_id, store_id, product_id, product_qty)

## remote sales
msr_remote_sales_re <- select(msr_remote_sales_re,
                              submission_date, staff_id, store_id, product_id, product_qty)

## combine
msr_final_sales <- bind_rows(msr_sales_re, msr_remote_sales_re)

## -----------------------------------------------------------------------------
##

msr_final_sales <- gen_ymd(msr_final_sales)
msr_final_sales$product_qty <- as.double(msr_final_sales$product_qty)

## aggregate sales by month

msr_sales_permonth <- msr_final_sales %>%
    group_by(year, month, staff_id, store_id, product_id) %>%
    summarise(n_sales = sum(product_qty)) %>%
    ungroup() %>%
    mutate(product_id = paste0("sell", product_id)) %>%
    spread(product_id, n_sales)

## aggregate sales per day

msr_sales_perday <- msr_final_sales %>%
    group_by(date, staff_id, store_id, product_id) %>%
    summarise(n_sales = sum(product_qty)) %>%
    ungroup() %>%
    mutate(product_id = paste0("sell", product_id)) %>%
    spread(product_id, n_sales)

## -----------------------------------------------------------------------------
## Inventory

msr_inventory_re <- select(msr_inventory_re,
                           submission_date, staff_id, store_id,
                           product_id, product_qty)

msr_inventory_re <- gen_ymd(msr_inventory_re)
msr_inventory_re$product_qty <- as.double(msr_inventory_re$product_qty)

## aggregate inventory by month

msr_inventory_permonth <- msr_inventory_re %>%
    group_by(year, month, staff_id, store_id, product_id) %>%
    summarise(n_inventory = sum(product_qty)) %>%
    ungroup() %>%
    mutate(product_id = paste0("invt", product_id)) %>%
    spread(product_id, n_inventory)

## aggregate inventory per day

msr_inventory_perday <- msr_inventory_re %>%
    group_by(date, staff_id, store_id, product_id) %>%
    summarise(n_inventory = sum(product_qty)) %>%
    ungroup() %>%
    mutate(product_id = paste0("invt", product_id)) %>%
    spread(product_id, n_inventory)

## -----------------------------------------------------------------------------
## Calculate actual sales per day

msr_sales_permonth <- left_join(msr_sales_permonth, msr_inventory_permonth,
                                by = c("year", "month", "staff_id", "store_id"))

product_colnames1 <- names(msr_sales_permonth)[grepl("sell|invt", names(msr_sales_permonth))]

msr_sales_permonth[, product_colnames1] <- lapply(msr_sales_permonth[, product_colnames1],
                                                 function(x) {x[is.na(x)] <- 0; x})

msr_sales_permonth <- mutate(msr_sales_permonth,
                             finalKM8936136010014 = sellKM8936136010014 - invtKM8936136010014,
                             finalKM8936136010021 = sellKM8936136010021 - invtKM8936136010021)

msr_sales_permonth <- left_join(msr_sales_permonth,
                                select(msr_staff, staff_id, staff_lb, supasm_id, supasm_lb,
                                     suprsm_id, suprsm_lb, supsd_id, supsd_lb, region_id, region_lb),
                                by = "staff_id")

msr_sales_permonth <- left_join(msr_sales_permonth,
                                select(msr_store, store_id, store_lb, store_add),
                                by = "store_id")

## -----------------------------------------------------------------------------
## Calculate actual by month

msr_sales_perday <- left_join(msr_sales_perday, msr_inventory_perday,
                              by = c("date", "staff_id", "store_id"))

product_colnames2 <- names(msr_sales_perday)[grepl("sell|invt", names(msr_sales_perday))]

msr_sales_perday[, product_colnames2] <- lapply(msr_sales_perday[, product_colnames2],
                                                function(x) {x[is.na(x)] <- 0; x})

msr_sales_perday <- mutate(msr_sales_perday,
                           finalKM8936136010014 = sellKM8936136010014 - invtKM8936136010014,
                           finalKM8936136010021 = sellKM8936136010021 - invtKM8936136010021)

msr_sales_perday <- left_join(msr_sales_perday,
                              select(msr_staff, staff_id, staff_lb, supasm_id, supasm_lb,
                                     suprsm_id, suprsm_lb, supsd_id, supsd_lb, region_id, region_lb),
                              by = "staff_id")

msr_sales_perday <- left_join(msr_sales_perday,
                              select(msr_store, store_id, store_lb, store_add),
                              by = "store_id")

## -----------------------------------------------------------------------------
## filtering data by user role

role_mapping <- make_dict(msr_staff$username, msr_staff$user_role)
staff_dict <- make_dict(msr_staff$username, msr_staff$staff_id)

if (sys_user != "anchu") {
    user_name <- '$$FilterValue::get_user_info("##USERNAME##","username")$$'
    user_role <- encode(user_name, role_mapping)
    user_id <- encode(user_name, staff_dict)

    if (user_role == "SR") {
        msr_sales_perday <- filter(msr_sales_perday, staff_id == user_id)
        msr_sales_permonth <- filter(msr_sales_permonth, staff_id == user_id)
    }

    if (user_role == "ASM") {
        msr_sales_perday <- filter(msr_sales_perday, supasm_id == user_id)
        msr_sales_permonth <- filter(msr_sales_permonth, supasm_id == user_id)
    }

    if (user_role == "RSM") {
        msr_sales_perday <- filter(msr_sales_perday, suprsm_id == user_id)
        msr_sales_permonth <- filter(msr_sales_permonth, suprsm_id == user_id)
    }

    if (user_role == "SD") {
        msr_sales_perday <- filter(msr_sales_perday, supsd_id == user_id)
        msr_sales_permonth <- filter(msr_sales_permonth, supsd_id == user_id)
    }
}

## -----------------------------------------------------------------------------
## inputs to input-panels

input_years <- 2017:current_year()
input_months <- 1:12
input_salesrep <- letters

```



```{r, include=FALSE}

re_msr_sales <- reactive({
    if (input$shown_by_ip == "select_month") {
        out <- filter(msr_sales_permonth, year %in% input$year_ip & month %in% input$month_ip)
        out <- select(out, supsd_lb, suprsm_lb, supasm_lb, staff_lb, region_lb, store_lb, store_add,
                  sellKM8936136010014, sellKM8936136010021,
                  invtKM8936136010014, invtKM8936136010021,
                  finalKM8936136010014, finalKM8936136010021)
    } else {
        out <- filter(msr_sales_perday, date %in% input$date_ip)
        out <- select(out, date, supsd_lb, suprsm_lb, supasm_lb, staff_lb, region_lb, store_lb, store_add,
                  sellKM8936136010014, sellKM8936136010021,
                  invtKM8936136010014, invtKM8936136010021,
                  finalKM8936136010014, finalKM8936136010021)
    }
    names(out) <- encode(names(out), colnames_dict)
    out
})

output$sales_tbl <- DT::renderDataTable(
{re_msr_sales()},
class = "nowrap stripe hover cell-border",
rownames = FALSE,
options = list(scrollX = TRUE,
               ordering = FALSE,
               pageLength = 20,
               language = list(url = "//cdn.datatables.net/plug-ins/1.10.7/i18n/Vietnamese.json"))
)

output$sales_xls <- downloadHandler(
    filename = paste0("KINGSMEN_Sellout", format(Sys.time(), "%d%m%Y_%H%M"), ".xlsx"),
    content = function(file) {
        ## make workbook
        wb <- create_excel_file(re_msr_sales(),
                                sheet_name = "Sheet 1",
                                sheet_title = c("Danh sách NT Mua hàng"))
        ## save workbook to a file
        saveWorkbook(wb, file)
    }
)


```




Inputs {.sidebar}
-------------------------------------

```{r}


fluidRow(
    column(
        width = 12,
        tags$br(),
        radioButtons(
            inputId = "shown_by_ip",
            label = tags$strong("Chọn xem dữ liệu theo:"),
            choices = c("Ngày" = "select_day",
                        "Tháng" = "select_month")
        )
    )
)

fluidRow(
    column(
        width = 12,
        tags$br(),
        renderUI({

            if (input$shown_by_ip == "select_day") {
                fluidRow(
                    column(
                        width = 12,
                        dateInput(
                            inputId = "date_ip",
                            label = tags$strong("Chọn ngày:"),
                            value = Sys.Date(),
                            max = Sys.Date(),
                            format = "dd-mm-yyyy"
                        )
                    )
                )

            } else if (input$shown_by_ip == "select_month") {

                fluidRow(
                    column(
                        width = 12,
                        numericInput(
                            inputId = "year_ip",
                            label = tags$strong("Chọn năm:"),
                            value = current_year(),
                            min = min(input_years, na.rm = TRUE),
                            max = max(input_years, na.rm = TRUE)
                        ),
                        numericInput(
                            inputId = "month_ip",
                            label = tags$strong("Chọn tháng:"),
                            value = current_month(),
                            min = min(input_months, na.rm = TRUE),
                            max = max(input_months, na.rm = TRUE)
                        )
                    )
                )
            }
        })
    )
)

```

Column
-------------------------------------

### Doanh số bán hàng theo nhà thuốc

```{r}

fluidRow(
    column(
        width = 12,
        DT::dataTableOutput(outputId = "sales_tbl")
    )
)

fluidRow(
    column(
        width = 1,
        downloadButton(outputId = "sales_xls", "xls")
    )
)

```
