---
title: "Báo cáo số lượng khách hàng NPP"
author: "Real - time Analytics"
date: "`r format(Sys.time(), '%d-%m-%Y %H:%M:%S')`"
runtime: shiny
output:
    flexdashboard::flex_dashboard:
        orientation: rows
        theme: flatly
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, comment = "", message = FALSE, warning = FALSE)
Sys.setlocale(category='LC_ALL','en_US.UTF-8')
options(shiny.sanitize.errors = FALSE, scipen = 999) # large numbers should be in full display
sys_user <- Sys.info()["user"]

```



```{r helper-functions, include=FALSE}

table <- function(..., useNA = 'ifany') base::table(..., useNA = useNA)

gen_ymd <- function(x, which = "ymd", by = c("work_date")) {
    by <- match.arg(by)
    if (!any(names(x) == by)) {
        stop(sprintf("column '%s' can not be found", by), call. = FALSE)
    }
    
    x[[by]] <- lubridate::dmy(x[[by]])

    if (grepl("y", which)) {
        x$year <- lubridate::year(x[[by]])
    }

    if (grepl("m", which)) {
        x$month <- lubridate::month(x[[by]])
    }

    if (grepl("d", which)) {
        x$date <- lubridate::date(x[[by]])
    }
    x
}
```


```{r packages, include=FALSE}

## -----------------------------------------------------------------------------
## load packages

pkgs <- c("tidyr", "dplyr", "shiny", "xlsx", "RTA", "readr")
sapply(pkgs, require, character.only = TRUE)


switch(
    sys_user,
    dieulinh = {library("DT")},
    {library("DT", lib.loc = "/home/haoly/R/library/DT-1.0.0")}
)

```


```{r import-data, include=FALSE}

## -----------------------------------------------------------------------------
## import data


switch(
    sys_user,
    dieulinh = {
      data_dir <- "~/MEGAsync/RTA/KINGSMEN/data/"
    
      try(npp_handover_order <- read_csv(paste0(data_dir, "NPP_HANDOVER_ORDER_TEST/NPP_HANDOVER_ORDER_TEST.csv"), col_types = cols(.default = "c")))
      try(npp_handover_order_rr <- read_csv(paste0(data_dir, "NPP_HANDOVER_ORDER_TEST/npp_rr.csv"), col_types = cols(.default = "c")))
      try(all_handover_order_rr <- read_csv(paste0(data_dir, "NPP_HANDOVER_ORDER_TEST/all_rr.csv"), col_types = cols(.default = "c")))
      try(msr_sales <- read_csv(paste0(data_dir, "MSR_SALES_DEMO/MSR_SALES_DEMO.csv"), col_types = cols(.default = "c")))
      try(msr_sales_rr <- read_csv(paste0(data_dir, "MSR_SALES_DEMO/sales_rr.csv"), col_types = cols(.default = "c")))
      try(msr_remote <- read_csv(paste0(data_dir, "MSR_SALES_REMOTE_DEMO/MSR_SALES_REMOTE_DEMO.csv"), col_types = cols(.default = "c")))
      try(msr_remote_rr <- read_csv(paste0(data_dir, "MSR_SALES_REMOTE_DEMO/sales_rr.csv"), col_types = cols(.default = "c")))
      try(msr_checkin <- read_csv(paste0(data_dir, "MSR_CHECKIN_DEMO/MSR_CHECKIN_DEMO.csv"), col_types = cols(.default = "c")))
      #try(msr_product <- get_dm_data("C011", "MSR_product"))
      #try(msr_storeedit <- read_csv(paste0(data_dir, "MSR_NEWEDIT_STORE_DEMO/MSR_NEWEDIT_STORE_DEMO.csv"), col_types = cols(.default = "c")))
      #try(msr_store <- read_csv(paste0(data_dir, "MSR_store.csv"), col_types = cols(.default = "c")))
      #try(msr_staff <- read_csv(paste0(data_dir, "MSR_staff.csv"), col_types = cols(.default = "c")))
     
    }, {
      try(npp_handover_order <- get_family_data("C011", "NPP_HANDOVER_ORDER"))
      try(npp_handover_order_rr <- get_family_data("C011", "NPP_HANDOVER_ORDER", "npp_rr"))
      try(all_handover_order_rr <- get_family_data("C011", "NPP_HANDOVER_ORDER", "all_rr"))
      try(msr_sales <- get_family_data("C011", "MSR_SALES_DEMO"))
      try(msr_sales_rr <- get_family_data("C011", "MSR_SALES_DEMO", "sales_rr"))
      try(msr_remote <- get_family_data("C011", "MSR_SALES_REMOTE_DEMO"))
      try(msr_remote_rr <- get_family_data("C011", "MSR_SALES_REMOTE_DEMO", "sales_rr"))
      try(msr_checkin <- get_family_data("C011", "MSR_CHECKIN_DEMO"))
      #try(msr_product <- get_dm_data("C011", "MSR_product"))
      try(msr_storeedit <- get_dm_data("C011", "MSR_newedit_store"))
      try(msr_store <- get_dm_data("C011", "MSR_store"))
      try(msr_staff <- get_dm_data("C011", "MSR_staff"))

    }
)

try(msr_storeedit <- get_dm_data("C011", "MSR_newedit_store"))
try(msr_store <- get_dm_data("C011", "MSR_store"))
try(msr_staff <- get_dm_data("C011", "MSR_staff"))



#colname_out_month <- c("SD", "RSM", "ASM", "NPP", "SR", "Địa bàn", "Số lượng NT đang phục vụ thăm viếng", "Số lượng NT mua hàng", "Tỷ lệ KH mua hàng")

#colname_out_day <- c("Ngày", colname_out_month)

colname_out_month <- c("SD", "RSM", "ASM", "NPP", "Mã SR", "SR", "Loại hình NT", "Số lượng NT mua hàng", "Tỷ lệ KH mua hàng")

colname_out_day <- c("Ngày", colname_out_month)

```


```{r prepare-data, include=FALSE}

## -----------------------------------------------------------------------------
## join data

msr_store <- filter(msr_store, marked_as_deleted == 0)
msr_storeedit <- filter(msr_storeedit, marked_as_deleted == 0)
msr_staff <- filter(msr_staff, marked_as_deleted == 0)

msr_checkin <- replace_with_na(msr_checkin)
#msr_checkin <- filter(msr_checkin, !grepl("^DGW|TEST|^BDUST", store_id))


msr_sales <- replace_with_na(msr_sales)
msr_remote <- replace_with_na(msr_remote)

msr_sales_remote <- bind_rows(msr_sales, msr_remote)
msr_sales_remote <- filter(msr_sales_remote, !grepl("^DGW|TEST|^BDUST", store_id))

msr_storeedit <- msr_storeedit %>% 
                  select(store_id, store_lb, 
                         store_hnumber, store_street, store_ward_lb, 
                         store_district_lb, city_lb, 
                         store_add, store_phone, store_owner_name,
                         salerep_id = staff_id, salerep_lb = fullname)

store <- bind_rows(msr_store, msr_storeedit)
store[store == ""] <- NA
#store$store_type_id[is.na(store$store_type_id)] <- "NA"
#store$store_type_lb[is.na(store$store_type_lb)] <- "Chưa có loại hình"

#Change type Date
msr_sales_remote$work_date <- lubridate::dmy(msr_sales_remote$work_date)
msr_checkin$work_date <- lubridate::dmy(msr_checkin$work_date)

## remove testing instances

msr_staff <- filter(msr_staff, username != "dgw_vthieu")
msr_staff <- filter(msr_staff, grepl("^dgw", username))

msr_sales_remote <- filter(msr_sales_remote, username != "dgw_vthieu")
#msr_sales_remote <- filter(msr_sales_remote, grepl("^dgw", username))

msr_checkin <- filter(msr_checkin, username != "dgw_vthieu")
#msr_checkin <- filter(msr_checkin, grepl("^dgw", username))

```


```{r calculation, include=FALSE}

## -----------------------------------------------------------------------------
##Join data store
msr_sales_remote <- left_join(msr_sales_remote, 
                              select(store, store_type_id, store_id),
                              by = "store_id")

sales_remote <- msr_sales_remote %>% 
  select(work_date, staff_id, store_id, store_type_id) %>% unique()


## -----------------------------------------------------------------------------
##Count by type store
count_by_type <- sales_remote %>% 
  count(work_date, staff_id, store_type_id) %>% 
  rename(count_type = n) 

##Count all store
count_total_type <- sales_remote %>% 
  count(work_date, staff_id) %>% 
  rename(count_total = n)

##Join 2 count data
count_customer <- left_join(count_by_type, count_total_type, 
                            by = c("work_date", "staff_id"))

count_customer <- left_join(count_customer, 
                            select(msr_staff, staff_id, staff_lb, supsd_id, supsd_lb, 
                                   suprsm_id, suprsm_lb, 
                                   supasm_id, supasm_lb, npp_id, npp_lb, staff_region),
                            by = "staff_id")

#count_customer$store_type_id[is.na(count_customer$store_type_id)] <- "None"


## -----------------------------------------------------------------------------
##Count checkin data
msr_sales_remote <- left_join(msr_sales_remote, 
                              select(store, store_type_id, store_id),
                              by = "store_id")

checkin <- msr_checkin %>% 
  select(work_date, staff_id, store_id) %>% unique()
  

count_checkin <- checkin %>% 
  count(work_date, staff_id) %>% 
  rename(count_checkin = n)

## -----------------------------------------------------------------------------
##Store not buy
count_customer2 <- count_customer %>% 
  group_by(work_date, staff_id) %>% 
  summarise(count_type = sum(count_type, na.rm = T)) %>% 
  ungroup()


count_customer2 <- full_join(count_customer2, count_checkin, 
                             by = c("work_date", "staff_id"))


count_customer2$count_type[is.na(count_customer2$count_type)] <- 0 


count_customer2$count_store_notbuy <- count_customer2$count_checkin - count_customer2$count_type

##Join data final
count_customer2 <- filter(count_customer2, count_store_notbuy > 0)

count_customer2 <- left_join(count_customer2, 
                             select(msr_staff, staff_id, staff_lb, supsd_id, supsd_lb, 
                                   suprsm_id, suprsm_lb, 
                                   supasm_id, supasm_lb, npp_id, npp_lb, staff_region),
                            by = "staff_id")


## -----------------------------------------------------------------------------
##List store not buy
sales_remote$check <- rep(1, nrow(sales_remote))

sale_check <- left_join(checkin, sales_remote, by = c("work_date", "staff_id", "store_id"))

#sale_check <- filter(sale_check, !(check %in% 1))

sale_check <- sale_check %>% unique()

##Join data final
final_store <- left_join(sale_check, select(store, -store_type_id), 
                                          by = c("store_id"))

#store_not_sale <- left_join(store_not_sale, npp, by = c("staff_id" = "salerep_id"))
final_store <- left_join(final_store, 
                            select(msr_staff, staff_id, staff_lb, supsd_id, supsd_lb, 
                                   suprsm_id, suprsm_lb, 
                                   supasm_id, supasm_lb, npp_id, npp_lb, staff_region),
                            by = "staff_id")



## -----------------------------------------------------------------------------
## filtering data by user role

role_mapping <- make_dict(msr_staff$username, msr_staff$user_role)
staff_dict <- make_dict(msr_staff$username, msr_staff$staff_id)

if (sys_user != "dieulinh") {
    #user_name <- "dgw_duhtrang"
    user_name <- '$$FilterValue::get_user_info("##USERNAME##","username")$$'
    user_role <- encode(user_name, role_mapping)
    user_id <- encode(user_name, staff_dict)
    
    if (user_role == "SR") {
        count_customer <- filter(count_customer, staff_id == user_id)
        count_customer2 <- filter(count_customer2, staff_id == user_id)
        final_store  <- filter(final_store , staff_id == user_id)
    }

    if (user_role == "NPP") {
        count_customer <- filter(count_customer, npp_id == user_id)
        count_customer2 <- filter(count_customer2, npp_id == user_id)
        final_store <- filter(final_store , npp_id == user_id)
    }

    if (user_role == "ASM") {
        count_customer <- filter(count_customer, supasm_id == user_id)
        count_customer2 <- filter(count_customer2, supasm_id == user_id)
        final_store <- filter(final_store , supasm_id == user_id)
    }

    if (user_role == "RSM") {
        count_customer <- filter(count_customer, suprsm_id == user_id)
        count_customer2 <- filter(count_customer2, suprsm_id == user_id)
        final_store <- filter(final_store , suprsm_id == user_id)
    }

    if (user_role == "SD") {
        count_customer <- filter(count_customer, supsd_id == user_id)
        count_customer2 <- filter(count_customer2, supsd_id == user_id)
        final_store <- filter(final_store , supsd_id == user_id)
    }
}

## -----------------------------------------------------------------------------
## inputs to input-panels

input_years <- 2017:current_year()
input_months <- c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")

input_dates <- unique(c(msr_sales_remote$work_date, msr_checkin$work_date))

#input_type <- unique(store$store_type_id)
#store$store_type_id[is.na(store$store_type_id)] <- "None"
#store$store_type_lb[is.na(store$store_type_lb)] <- "Chưa phân loại"
input_type <- distinct(select(msr_store, store_type_id, store_type_lb))
input_type <- filter(input_type, store_type_id != "", !is.na(store_type_id))
input_type <- c("Tất cả" = "All", make_dict(input_type$store_type_lb, input_type$store_type_id))

input_level <- c("RSM", "ASM", "NPP", "SR")

input_SR <- distinct(select(msr_staff, staff_id, staff_lb))
input_SR <- filter(input_SR, staff_id != "", !is.na(staff_id))
input_SR <- c("Tất cả" = "All", make_dict(input_SR$staff_lb, input_SR$staff_id))

input_NPP <- distinct(select(msr_staff, npp_id, npp_lb))
input_NPP <- filter(input_NPP, npp_id != "", !is.na(npp_id))
input_NPP <- c("Tất cả" = "All", make_dict(input_NPP$npp_lb, input_NPP$npp_id))

input_ASM <- distinct(select(msr_staff, supasm_id, supasm_lb))
input_ASM <- filter(input_ASM, supasm_id != "", !is.na(supasm_id))
input_ASM <- c("Tất cả" = "All", make_dict(input_ASM$supasm_lb, input_ASM$supasm_id))

input_RSM <- distinct(select(msr_staff, suprsm_id, suprsm_lb))
input_RSM <- filter(input_RSM, suprsm_id != "", !is.na(suprsm_id))
input_RSM <- c("Tất cả" = "All", make_dict(input_RSM$suprsm_lb, input_RSM$suprsm_id))
```



```{r server-processing}

out_table <- reactive({
  if (input$shown_by_report == "buy") {
      if (input$shown_by_ip == "select_day") {
        
      validate(
        need(input$date_ip[1] <= input$date_ip[2], 
             "Khoảng thời gian bắt đầu phải nhỏ hơn thời gian kết thúc"))
          
      out <- filter(count_customer,
                    work_date <= input$date_ip[2], work_date >= input$date_ip[1])
      
      if (input$select_type != "All") {  
      out <- filter(out, store_type_id %in% input$select_type)
      }
      
      if (input$sup_ip == "select_rsm") {
	  out <- out
	  if (input$rsm_ip != "All") {  
        out <- filter(out, suprsm_id %in% input$rsm_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của RSM này. Vui lòng chọn RSM khác."))
				 }
    }

    if (input$sup_ip == "select_asm") {
	  out <- out
	  if (input$asm_ip != "All") {  
        out <- filter(out, supasm_id %in% input$asm_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của ASM này. Vui lòng chọn ASM khác."))
		}
    }

    if (input$sup_ip == "select_npp") {
	  out <- out
	  if (input$sr_ip != "All") {  
        out <- filter(out, npp_id %in% input$npp_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của NPP này. Vui lòng chọn NPP khác."))
		}
    }
    
    if (input$sup_ip == "select_sr") {
	  out <- out
	  if (input$sr_ip != "All") {  
        out <- filter(out, staff_id %in% input$sr_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của SR này. Vui lòng chọn SR khác."))
		}
    }
      
      validate(
            need(nrow(out) > 0, "Không có dữ liệu trong khoảng thời gian này."))
      
      out$per_sale <- round(out$count_type *100 / out$count_total, 2)
      
      out <- out[, c("work_date", "staff_region",
                      "supsd_lb",  "suprsm_lb",  "supasm_lb", "npp_lb", "staff_id", "staff_lb", 
                      "store_type_id",
                      "count_type", "per_sale")]
      colname_out <- make_dict(c("work_date", "staff_region",
                      "supsd_lb", "suprsm_lb", "supasm_lb", "npp_lb", "staff_id", "staff_lb", 
                      "store_type_id",
                      "count_type", "per_sale"), c("Ngày","Địa bàn","SD", "RSM", "ASM", "NPP",
												  "Mã SR", "SR", "Loại KH", "Số lượng", "Tỷ lệ"))
	  names(out) <- encode(names(out), colname_out)
      
    } else {
      
      month_ip <- paste0(input$month_ip, "/", input$year_ip)
      count_customer$month <- format(count_customer$work_date, "%m/%Y")
      
      out <- count_customer %>% 
        group_by(month, staff_id, store_type_id) %>% 
        summarise(count_type = sum(count_type, na.rm = T),
                  count_total = sum(count_total, na.rm = T),
                  per_sale = round(count_type*100 / count_total, 2)) %>% 
        ungroup()
      
      out <- filter(out, month %in% month_ip)
      out <- left_join(out, 
                       select(msr_staff, staff_id, staff_lb, supsd_id, supsd_lb, 
                             suprsm_id, suprsm_lb, 
                             supasm_id, supasm_lb, npp_id, npp_lb, staff_region),
                            by = "staff_id")
      
      if (input$select_type != "All") {  
      out <- filter(out, store_type_id %in% input$select_type)
      }
      
      if (input$sup_ip == "select_rsm") {
	  out <- out
	  if (input$rsm_ip != "All") {  
        out <- filter(out, suprsm_id %in% input$rsm_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của RSM này. Vui lòng chọn RSM khác."))
				 }
    }

    if (input$sup_ip == "select_asm") {
	  out <- out
	  if (input$asm_ip != "All") {  
        out <- filter(out, supasm_id %in% input$asm_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của ASM này. Vui lòng chọn ASM khác."))
		}
    }

    if (input$sup_ip == "select_npp") {
	  out <- out
	  if (input$sr_ip != "All") {  
        out <- filter(out, npp_id %in% input$npp_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của NPP này. Vui lòng chọn NPP khác."))
		}
    }
    
    if (input$sup_ip == "select_sr") {
	  out <- out
	  if (input$sr_ip != "All") {  
        out <- filter(out, staff_id %in% input$sr_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của SR này. Vui lòng chọn SR khác."))
		}
    }
      
      validate(
        need(nrow(out) > 0, "Không có dữ liệu trong khoảng thời gian này."))
      
      
      out <- out[, c("supsd_lb", "suprsm_lb", "supasm_lb", "npp_lb", "staff_id", "staff_lb", 
                      "store_type_id",
                      "count_type", "per_sale")]
      colname_out <- make_dict(c("supsd_lb",  "suprsm_lb", "supasm_lb", "npp_lb", "staff_id", "staff_lb", 
                      "store_type_id",
                      "count_type", "per_sale"), c("SD", "RSM", "ASM", "NPP",
												  "Mã SR", "SR", "Loại KH", "Số lượng", "Tỷ lệ"))
	  names(out) <- encode(names(out), colname_out)
    }
  } 
  if (input$shown_by_report == "not_buy") {
    if (input$shown_by_ip == "select_day") {
        validate(
          need({input$date_ip[1] <= input$date_ip[2]}, 
               "Khoảng thời gian bắt đầu phải nhỏ hơn thời gian kết thúc"))
          
        out <- filter(count_customer2,
                      work_date <= input$date_ip[2], work_date >= input$date_ip[1])
        
        validate(need(nrow(out) > 0, ""))
        
        if (input$sup_ip == "select_rsm") {
	  out <- out
	  if (input$rsm_ip != "All") {  
        out <- filter(out, suprsm_id %in% input$rsm_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của RSM này. Vui lòng chọn RSM khác."))
				 }
    }

    if (input$sup_ip == "select_asm") {
	  out <- out
	  if (input$asm_ip != "All") {  
        out <- filter(out, supasm_id %in% input$asm_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của ASM này. Vui lòng chọn ASM khác."))
		}
    }

    if (input$sup_ip == "select_npp") {
	  out <- out
	  if (input$sr_ip != "All") {  
        out <- filter(out, npp_id %in% input$npp_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của NPP này. Vui lòng chọn NPP khác."))
		}
    }
    
    if (input$sup_ip == "select_sr") {
	  out <- out
	  if (input$sr_ip != "All") {  
        out <- filter(out, staff_id %in% input$sr_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của SR này. Vui lòng chọn SR khác."))
		}
    }
        
        out <- out[, c("work_date", 
                       "supsd_lb", "suprsm_lb", "supasm_lb", "npp_lb","staff_id", "staff_lb", 
                       "count_store_notbuy")]
        colname_out <- make_dict(c("work_date","supsd_lb", "suprsm_lb", "supasm_lb", "npp_lb", "staff_id", "staff_lb", 
                     "count_store_notbuy"), c("Ngày","SD", "RSM", "ASM", "NPP",
												  "Mã SR", "SR", "Số lượng"))
	  names(out) <- encode(names(out), colname_out)
      
    } else {
      
        month_ip <- paste0(input$month_ip, "/", input$year_ip)
        count_customer2$month <- format(count_customer2$work_date, "%m/%Y")
        
        out <- count_customer2 %>% 
          group_by(month, staff_id) %>% 
          summarise(count_type = sum(count_type, na.rm = T),
                    count_checkin = sum(count_checkin, na.rm = T),
                    count_store_notbuy = count_checkin - count_type) %>% 
          ungroup()
        
        out <- filter(out, month %in% month_ip)
        
        validate(
          need(nrow(out) > 0, ""))
        

        out <- left_join(out, 
                         select(msr_staff, staff_id, staff_lb, supsd_id, supsd_lb, 
                               suprsm_id, suprsm_lb, 
                               supasm_id, supasm_lb, npp_id, npp_lb),
                              by = "staff_id")
        
        if (input$sup_ip == "select_rsm") {
	  out <- out
	  if (input$rsm_ip != "All") {  
        out <- filter(out, suprsm_id %in% input$rsm_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của RSM này. Vui lòng chọn RSM khác."))
				 }
    }

    if (input$sup_ip == "select_asm") {
	  out <- out
	  if (input$asm_ip != "All") {  
        out <- filter(out, supasm_id %in% input$asm_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của ASM này. Vui lòng chọn ASM khác."))
		}
    }

    if (input$sup_ip == "select_npp") {
	  out <- out
	  if (input$sr_ip != "All") {  
        out <- filter(out, npp_id %in% input$npp_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của NPP này. Vui lòng chọn NPP khác."))
		}
    }
    
    if (input$sup_ip == "select_sr") {
	  out <- out
	  if (input$sr_ip != "All") {  
        out <- filter(out, staff_id %in% input$sr_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của SR này. Vui lòng chọn SR khác."))
		}
    }
        
        out <- out[, c("supsd_lb", "suprsm_lb", "supasm_lb", "npp_lb", "staff_id", "staff_lb",
                      "count_store_notbuy")]
        colname_out <- make_dict(c("supsd_lb", "suprsm_lb", "supasm_lb","npp_lb", "staff_id", "staff_lb", 
                     "count_store_notbuy"), c("SD", "RSM",  "ASM", "NPP",
												  "Mã SR", "SR", "Số lượng"))
	 names(out) <- encode(names(out), colname_out)
    }
    
  }
    
    
 out <- as.data.frame(out)   
 out 
})



out_table1 <- reactive({
    
    if (input$shown_by_ip == "select_day") {
      validate(
        need({input$date_ip[1] <= input$date_ip[2]}, 
             "Khoảng thời gian bắt đầu phải nhỏ hơn thời gian kết thúc"))
        
      out <- filter(final_store ,
                    work_date <= input$date_ip[2], work_date >= input$date_ip[1])
      
    } else {
      month_ip <- paste0(input$month_ip, "/", input$year_ip)
      final_store$month <- format(final_store$work_date, "%m/%Y")
      
      out <- filter(final_store, month %in% month_ip)
      
    }
    
    
  if (input$shown_by_report == "not_buy") {
    out <- filter(out, !(check %in% 1))  
    } else {
    out <- filter(out, check %in% 1)
     if (input$select_type != "All") {  
      out <- filter(out, store_type_id %in% input$select_type)
      }
    }
    
 
    if (input$sup_ip == "select_rsm") {
	  out <- out
	  if (input$rsm_ip != "All") {  
        out <- filter(out, suprsm_id %in% input$rsm_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của RSM này. Vui lòng chọn RSM khác."))
				 }
    }

    if (input$sup_ip == "select_asm") {
	  out <- out
	  if (input$asm_ip != "All") {  
        out <- filter(out, supasm_id %in% input$asm_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của ASM này. Vui lòng chọn ASM khác."))
		}
    }

    if (input$sup_ip == "select_npp") {
	  out <- out
	  if (input$sr_ip != "All") {  
        out <- filter(out, npp_id %in% input$npp_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của NPP này. Vui lòng chọn NPP khác."))
		}
    }
    
    if (input$sup_ip == "select_sr") {
	  out <- out
	  if (input$sr_ip != "All") {  
        out <- filter(out, staff_id %in% input$sr_ip)
		validate(need(nrow(out) > 0, "Không có dữ liệu của SR này. Vui lòng chọn SR khác."))
		}
    }
   
   out <- out[, c("work_date", "region_lb", "staff_region",
                     "npp_lb","staff_id", "staff_lb", 
                      "store_id", "store_lb", 
                      "store_hnumber", "store_street", "store_ward_lb", 
                      "store_district_lb", "city_lb", "store_add",
                      "store_phone", "store_owner_name")]
   colname_out <- make_dict(c("work_date", "region_lb", "staff_region",
                     "npp_lb","staff_id", "staff_lb", 
                      "store_id", "store_lb", 
                      "store_hnumber", "store_street", "store_ward_lb", 
                      "store_district_lb", "city_lb", "store_add",
                      "store_phone", "store_owner_name"), c("Ngày","Khu vực", "Địa bàn", "NPP",
												  "Mã SR", "SR", "Mã NT", "Tên NT", "Số nhà", "Đường", "Phường", "Quận/Huyện", "Tỉnh/Thành phố", "Địa chỉ", "SĐT", "Chủ NT"))
	  names(out) <- encode(names(out), colname_out)
   
  out  
})


output$output_tbl <- DT::renderDataTable(
    {out_table()},
    class = "nowrap stripe hover cell-border",
    rownames = FALSE,
   # filter = "top",
    options = list(scrollX=TRUE,
                   pageLength = 5,
                   language = list(url = "//cdn.datatables.net/plug-ins/1.10.7/i18n/Vietnamese.json"))
)



output$output_tbl1 <- DT::renderDataTable(
    {out_table1()},
    class = "nowrap stripe hover cell-border",
    rownames = FALSE,
   # filter = "top",
    options = list(scrollX=TRUE,
                   pageLength = 5,
                   language = list(url = "//cdn.datatables.net/plug-ins/1.10.7/i18n/Vietnamese.json"))
)

output$output_xls <- downloadHandler(

	filename = function() {
       filename = paste0("NUMBER_OF_CUSTOMER", format(Sys.time(), "%d%m%Y_%H%M%S"), ".xlsx")
    },
    content = function(file) {
        ## creation of the workbook
        wb <- createWorkbook(type = "xlsx")

        ## define style for workbook
        title_style <- CellStyle(wb) +
            Font(wb, heightInPoints = 14, color = "forestgreen", isBold = TRUE, underline = 0)

        subtitle_style <- CellStyle(wb) +
            Font(wb, heightInPoints = 12, isItalic = TRUE, isBold = FALSE)

        table_rownames_style <- CellStyle(wb) +
            Font(wb, isBold = FALSE)

        table_colnames_style <- CellStyle(wb) +
            Font(wb, isBold = TRUE) +
            Alignment(wrapText = TRUE, horizontal = "ALIGN_LEFT") +
            Border(color = "black", position = c("TOP", "BOTTOM"), pen = c("BORDER_THIN", "BORDER_THIN"))

        table_content_style <- CellStyle(wb,
                                         alignment = Alignment(wrapText = TRUE,
                                                               horizontal = "ALIGN_CENTER"))


        ## Add sheet content function
        add_df_to_sheet <- function(df_table, sheet_object){
            addDataFrame(
                df_table,
                sheet_object,
                startRow = 4,
                startColumn = 1,
                colnamesStyle = table_colnames_style,
                rownamesStyle = table_rownames_style,
                colStyle = table_content_style,
                row.names = FALSE)
        }

        xlsx_add_title <- function(sheet, row_index, title, title_style) {
            rows <- createRow(sheet, rowIndex = row_index)
            sheet_title <- createCell(rows, colIndex = 1)
            setCellValue(sheet_title[[1, 1]], title)
            setCellStyle(sheet_title[[1, 1]], title_style)

        }

        ## Create new sheet and add contents
        sheet1 <- createSheet(wb, sheetName = "Bảng số lượng khách hàng")
        sheet2 <- createSheet(wb, sheetName = "Bảng chi tiết khách hàng")
       
        xlsx_add_title(sheet1, row_index = 2, title = "Số lượng", title_style = title_style)
        xlsx_add_title(sheet2, row_index = 2, title = "Chi tiết", title_style = title_style)
       
        add_df_to_sheet(out_table(), sheet1)
        add_df_to_sheet(out_table1(), sheet2)
        
        setColumnWidth(sheet1, colIndex = c(1:ncol(out_table())), colWidth = 20)
        setColumnWidth(sheet2, colIndex = c(1:ncol(out_table1())), colWidth = 20)
        
        ## save workbook to a file
        saveWorkbook(wb, file)
    }
)
```

Inputs {.sidebar}
----------------------------------------------------------------------

```{r input-panel}
radioButtons(
            inputId = "shown_by_report",
            label = tags$strong("Chọn xem báo cáo:"),
            choices = c("Khách hàng mua hàng" = "buy",
                        "Khách hàng không mua hàng" = "not_buy")
        )

tags$br()

radioButtons(
            inputId = "shown_by_ip",
            label = tags$strong("Chọn xem dữ liệu theo:"),
            choices = c("Ngày" = "select_day",
                        "Tháng" = "select_month")
        )


tags$br()


conditionalPanel(
        condition = "input.shown_by_ip == 'select_day'",
        dateRangeInput(
                    inputId = "date_ip",
                    label = "Chọn ngày:",
                    min = min(input_dates),
                    max = Sys.Date(),
                    start = min(input_dates),
                    end = Sys.Date(),
                    format = "dd-mm-yyyy",
                    separator = "đến",
                    language = "vi"
        )
)

conditionalPanel(
  condition = "input.shown_by_ip == 'select_month'",
  selectInput(
                          inputId = "year_ip",
                          label = tags$strong("Chọn năm:"),
                          choices = input_years,
                          selected = current_year()
              )
)


conditionalPanel(
  condition = "input.shown_by_ip == 'select_month'",
  selectInput(
                            inputId = "month_ip",
                            label = tags$strong("Chọn tháng:"),
                            choices = input_months,
                            selected = current_month(as_char = T)
                )
)
 
tags$br()
conditionalPanel(
        condition = "input.shown_by_report == 'buy'",
        selectInput(
          inputId = "select_type",
          label = "Chọn loại khách hàng",
          choices = input_type
  
)
)
  
tags$br()
radioButtons(
    inputId = "sup_ip",
    label = tags$strong("Chọn cấp bậc:"),
    choices = c("RSM" = "select_rsm",
                "ASM" = "select_asm",
                "NPP" = "select_npp",
                "SR" = "select_sr")
)


conditionalPanel(
    condition = "input.sup_ip == 'select_rsm'",
    selectInput(
        inputId = "rsm_ip",
        label = tags$strong("Chọn RSM:"),
        choices = input_RSM
    )
)

conditionalPanel(
    condition = "input.sup_ip == 'select_asm'",
    selectInput(
        inputId = "asm_ip",
        label = tags$strong("Chọn ASM:"),
        choices = input_ASM
    )
)

conditionalPanel(
    condition = "input.sup_ip == 'select_npp'",
    selectInput(
        inputId = "npp_ip",
        label = tags$strong("Chọn NPP:"),
        choices = input_NPP
    )
)


conditionalPanel(
    condition = "input.sup_ip == 'select_sr'",
    selectInput(
        inputId = "sr_ip",
        label = tags$strong("Chọn SR:"),
        choices = input_SR
    )
)
tags$br()

fluidRow(
    column(
        width = 2,
        downloadButton(outputId = 'output_xls', label = 'xlsx')
        )
)

```

Row
-------------------------------------

### Bảng tổng hợp

```{r}

fluidRow(
    column(
        width = 12,
        DT::dataTableOutput(outputId = "output_tbl")
    )
)

```

Row
-------------------------------------

### Bảng tổng hợp chi tiết

```{r}

fluidRow(
    column(
        width = 12,
        DT::dataTableOutput(outputId = "output_tbl1")
    )
)



```
