---
title: "Báo cáo khảo sát điểm bán - Kingsmen"
date: "`r format(Sys.time(), '%d-%m-%Y %H:%M')`"
runtime: shiny
output:
    flexdashboard::flex_dashboard:
        theme: flatly
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, comment = "", message = FALSE, warning = FALSE)
Sys.setlocale(category='LC_ALL','en_US.UTF-8')
options(shiny.sanitize.errors = FALSE, scipen = 999) # large numbers should be in full display
sys_user <- Sys.info()["user"]

```

```{r import-data, include=FALSE}

## -----------------------------------------------------------------------------
## load packages

pkgs <- c("readr", "tidyr", "dplyr", "shiny", "xlsx", "RTA")
sapply(pkgs, require, character.only = TRUE)

switch(
    sys_user,
    dieulinh = {library("DT")},
    {library("DT", lib.loc = "/home/haoly/R/library/DT-1.0.0")}
)

## -----------------------------------------------------------------------------
## import data

switch(
    sys_user,
    anchu = {
        data_dir <- "~/rtanalytics-svnrepo/4.Analytics_South/1.Projects/2.Enterprises/1.DGW/Kingsmen/data/"
        try(sup_checkin <- read_csv(paste0(data_dir, "DGW_CHECKIN/DGW_CHECKIN_DEMO.csv"), col_types = cols(.default = "c")))
        try(sup_inventory <- read_csv(paste0(data_dir, "DGW_INVENTORY/DGW_INVENTORY_DEMO.csv"), col_types = cols(.default = "c")))
        try(sup_inventory_re <- read_csv(paste0(data_dir, "DGW_INVENTORY/dgw_rr.csv"), col_types = cols(.default = "c")))
        try(sup_posm <- read_csv(paste0(data_dir, "DGW_POSM/DGW_POSM_DEMO.csv"), col_types = cols(.default = "c")))
        try(sup_posm_re <- read_csv(paste0(data_dir, "DGW_POSM/dgw_rr.csv"), col_types = cols(.default = "c")))
        try(sup_competitor <- read_csv(paste0(data_dir, "DGW_COMPETITORS/DGW_COMPETITORS_DEMO.csv"), col_types = cols(.default = "c")))
        try(sup_competitor_re <- read_csv(paste0(data_dir, "DGW_COMPETITORS/dgw_rr.csv"), col_types = cols(.default = "c")))
        try(sup_survey_store <- read_csv(paste0(data_dir, "DGW_SURVEY_STORE/DGW_SURVEY_STORE_DEMO.csv"), col_types = cols(.default = "c")))
        try(sup_survey_game <- read_csv(paste0(data_dir, "DGW_SURVEY_GAME/DGW_SURVEY_GAME_DEMO.csv"), col_types = cols(.default = "c")))
        try(sup_checkout <- read_csv(paste0(data_dir, "DGW_CHECKOUT/DGW_CHECKOUT_DEMO.csv"), col_types = cols(.default = "c")))
    }, {
        try(sup_checkin <- get_family_data("C011", "DGW_CHECKIN_DEMO"))
        try(sup_inventory <- get_family_data("C011", "DGW_INVENTORY_DEMO"))
        try(sup_inventory_re <- get_family_data("C011", "DGW_INVENTORY_DEMO", "dgw_rr"))
        try(sup_posm <- get_family_data("C011", "DGW_POSM_DEMO"))
        try(sup_posm_re <- get_family_data("C011", "DGW_POSM_DEMO", "dgw_rr"))
        try(sup_competitor <- get_family_data("C011", "DGW_COMPETITORS_DEMO"))
        try(sup_competitor_re <- get_family_data("C011", "DGW_COMPETITORS_DEMO", "dgw_rr"))
        try(sup_survey_store <- get_family_data("C011", "DGW_SURVEY_STORE_DEMO"))
        try(sup_survey_game <- get_family_data("C011", "DGW_SURVEY_GAME_DEMO"))
        try(sup_checkout <- get_family_data("C011", "DGW_CHECKOUT_DEMO"))
    },
    dieulinh = {
        data_dir <- "/home/dieulinh/MEGAsync/RTA/KINGSMEN/raw_data/"
        try(sup_checkin <- read_csv(paste0(data_dir, "DGW_CHECKIN/DGW_CHECKIN_DEMO.csv"), col_types = cols(.default = "c")))
        try(sup_inventory <- read_csv(paste0(data_dir, "DGW_INVENTORY/DGW_INVENTORY_DEMO.csv"), col_types = cols(.default = "c")))
        try(sup_inventory_re <- read_csv(paste0(data_dir, "DGW_INVENTORY/dgw_rr.csv"), col_types = cols(.default = "c")))
        try(sup_posm <- read_csv(paste0(data_dir, "DGW_POSM/DGW_POSM_DEMO.csv"), col_types = cols(.default = "c")))
        try(sup_posm_re <- read_csv(paste0(data_dir, "DGW_POSM/dgw_rr.csv"), col_types = cols(.default = "c")))
        try(sup_competitor <- read_csv(paste0(data_dir, "DGW_COMPETITORS/DGW_COMPETITORS_DEMO.csv"), col_types = cols(.default = "c")))
        try(sup_competitor_re <- read_csv(paste0(data_dir, "DGW_COMPETITORS/dgw_rr.csv"), col_types = cols(.default = "c")))
        try(sup_survey_store <- read_csv(paste0(data_dir, "DGW_SURVEY_STORE/DGW_SURVEY_STORE_DEMO.csv"), col_types = cols(.default = "c")))
        try(sup_survey_game <- read_csv(paste0(data_dir, "DGW_SURVEY_GAME/DGW_SURVEY_GAME_DEMO.csv"), col_types = cols(.default = "c")))
      
    }
)

dgw_store <- get_dm_data("C011", "DGW_store")

```

```{r prepare-data, include=FALSE}

## merge repeats
sup_inventory_re <- left_join(sup_inventory_re, sup_inventory, by = "instanceID")
sup_posm_re <- left_join(sup_posm_re, sup_posm, by = "instanceID")
sup_competitor_re <- left_join(sup_competitor_re, sup_competitor, by = "instanceID")

## convert -999999
sup_checkin <- replace_with_na(sup_checkin)
sup_inventory_re <- replace_with_na(sup_inventory_re)
sup_posm_re <- replace_with_na(sup_posm_re)
sup_competitor_re <- replace_with_na(sup_competitor_re)
sup_survey_store <- replace_with_na(sup_survey_store)
sup_survey_game <- replace_with_na(sup_survey_game)
#sup_checkout <- replace_with_na(sup_checkout)

## -----------------------------------------------------------------------------
##

sup_posm_re <- select(sup_posm_re,
                      staff_id, region_id, work_date, work_time,
                      store_id, store_lb, store_add,
                      posm_id, posm_lb, posm_qty, image1,
                      posm_note, effective, content_share)

## -----------------------------------------------------------------------------
##

sup_inventory_re <- select(sup_inventory_re,
                           staff_id, region_id, work_date, work_time,
                           store_id, store_add, store_lb, product_id,
                           product_lb, product_qty, image)

## -----------------------------------------------------------------------------
##

sup_competitor_re <- select(sup_competitor_re,
                            staff_id, region_id, work_date, work_time,
                            store_id, store_add, store_lb,
                            company_id, company_lb, product,
                            product_lb, product_img, marketing,
                            marketing_img, marketing_content, fromdate,
                            todate, range, price_nomal, price_promote,
                            price_percent, prod_ingredient, prod_uses, prod_madein)

## -----------------------------------------------------------------------------
##

sup_survey_store <- select(sup_survey_store,
                           staff_id, region_id, work_date, work_time,
                           store_id, store_add, store_lb,
                           store_sales, store_reason, salerep_visit,
                           posm_length, posm_width, posm_height,
                           posm_img1, posm_exp_cal, posm_month_cal, posm_money,
                           competitor_name_cal, competitor_length, competitor_width,
                           competitor_height, competitor_img1, competitor_exp_cal,
                           competitor_month_cal, competitor_money)

## -----------------------------------------------------------------------------
##

sup_survey_game <- select(sup_survey_game,
                          staff_id, region_id, work_date, work_time,
                          store_id, store_add, store_lb,
                          player_name, player_phone,
                          dgw_01, dgw_02, dgw_03, dgw_04,
                          dgw_05, dgw_06, dgw_07, score_total)

## -----------------------------------------------------------------------------
##

input_staffs <- distinct(select(dgw_store, checker_id, checker_lb))
input_staffs <- make_dict(c("All", input_staffs$checker_lb),
                          c("all", input_staffs$checker_id))

input_regions <- distinct(select(dgw_store, region_id, region_lb))
input_regions <- filter(input_regions, region_id != "", !is.na(region_id))
input_regions <- make_dict(c("All", input_regions$region_lb),
                           c("all", input_regions$region_id))

```


```{r, include=FALSE}

## -----------------------------------------------------------------------------
##

inputModuleUI <- function(id) {

    ns <- NS(id)

    tagList(
        radioButtons(
            inputId = ns("group_ip"),
            label = tags$strong("Chọn xem báo cáo theo:"),
            choices = c("Nhân viên" = "select_staff",
                        "Khu vực" = "select_region")
        ),

        conditionalPanel(
            condition = sprintf("input['%s'] == 'select_staff'", ns("group_ip")),
            selectInput(
                inputId = ns("staff_ip"),
                label = tags$strong("Chọn nhân viên:"),
                choices = input_staffs
            )
        ),

        conditionalPanel(
            condition = sprintf("input['%s'] == 'select_region'", ns("group_ip")),
            selectInput(
                inputId = ns("region_ip"),
                label = tags$strong("Chọn khu vực:"),
                choices = input_regions
            )
        )
    )
}


filterData <- function(input, output, session, data) {
    reactive({

        if (input$group_ip == "select_staff") {

            if (input$staff_ip != "all") {
                out <- filter(data, staff_id %in% input$staff_ip)
            } else {
                out <- data
            }

        }

        if (input$group_ip == "select_region") {

            if (input$region_ip != "all") {
                out <- filter(data, region_id %in% input$region_ip)
            } else {
                out <- data
            }

        }

        return(out)

    })
}

dataTableModuleUI <- function(id) {
    ns <- NS(id)
fillRow(
  inputModuleUI(ns("ui")),
  fillCol(
    DT::dataTableOutput(outputId = ns("tbl")),
    fillRow(
    downloadButton(outputId = ns("tbl_xls"), label = "xlsx"),
    flex = c(NA)),
    flex = c(NA,3)
),
flex = c(1,7))
}

#downloadButtonModuleUI <- function(id) {
#  ns <- NS(id)
  
 # fluidRow(
  #  column(
  #    width = 6,
  #  inputModuleUI(ns("ui")),
  #  fluidRow(
  #    dataTableModuleUI(ns("ui")),
  #    )
  #  )
  #)
    
#}

renderDataTableModule <- function(input, output, session, data) {

    out <- callModule(filterData, id = "ui", data)

    output$tbl <- DT::renderDataTable(
    {out()},
    rownames = TRUE,
    class = "nowrap stripe hover cell-border",
    options = list(scrollX = TRUE,
                   ordering = TRUE,
                   pageLength = 15,
                   language = list(url = "//cdn.datatables.net/plug-ins/1.10.7/i18n/Vietnamese.json"))
    )
}

downloadHandlerModule <- function(input, output, session, data, filename, sheetname = filename, sheettitle = filename) {

    out <- callModule(filterData, id = "ui", data)

    output$tbl_xls <- downloadHandler(
    filename = paste0(filename, "_", format(Sys.time(), "%d%m%Y_%H%M%S"), ".xlsx"),
    content = function(file) {
        ## make workbook
        wb <- create_excel_file(out(),
                                sheet_name = sheetname,
                                sheet_title = sheettitle)
        ## save workbook to a file
        saveWorkbook(wb, file)
    }
)
    
}


```


POSM
================================================================================

#### Theo dõi trưng bày POSM


```{r}

tags$hr()

dataTableModuleUI(id = "posm")
#downloadButtonModuleUI(id = "posm")

callModule(renderDataTableModule, id = "posm", data = sup_posm_re)
callModule(downloadHandlerModule, id = "posm", data = sup_posm_re, filename = "POSM")
```

Hàng tồn kho
================================================================================

#### Cập nhật tồn kho


```{r}

tags$hr()

dataTableModuleUI(id = "inventory")
#downloadButtonModuleUI(id = "inventory")

callModule(renderDataTableModule, id = "inventory", data = sup_inventory_re)
callModule(downloadHandlerModule, id = "inventory", data = sup_inventory_re, filename = "INVENTORY")
```

Đối thủ cạnh tranh
================================================================================


#### Theo dõi đối thủ cạnh tranh


```{r}

tags$hr()

dataTableModuleUI(id = "competitor")
#downloadButtonModuleUI(id = "competitor")

callModule(renderDataTableModule, id = "competitor", data = sup_competitor_re)
callModule(downloadHandlerModule, id = "competitor", data = sup_competitor_re, filename = "COMPETITORS")
```


Khảo sát nhà thuốc
================================================================================

#### Khảo sát điểm bán


```{r}

tags$hr()

dataTableModuleUI(id = "survey_store")
#downloadButtonModuleUI(id = "survey_store")

callModule(renderDataTableModule, id = "survey_store", data = sup_survey_store)
callModule(downloadHandlerModule, id = "survey_store", data = sup_survey_store, filename = "SURVEY_STORE")

```


Tìm hiểu Kingsmen
================================================================================

#### Chương trình Tìm Hiểu Kingsmen Nhận Quà Hấp Dẫn

```{r}

tags$hr()

dataTableModuleUI(id = "survey_game")
#downloadButtonModuleUI(id = "survey_game")

callModule(renderDataTableModule, id = "survey_game", data = sup_survey_game)
callModule(downloadHandlerModule, id = "survey_game", data = sup_survey_game, filename = "SURVEY_GAME")

```
