---
title: "Báo cáo chỉ số bán hàng của Salesrep"
author: "Real-time Analytics"
date: "`r format(Sys.time(), '%d-%m-%Y %H:%M')`"
runtime: shiny
output:
    flexdashboard::flex_dashboard:
        theme: flatly
---

<style>
    body .main-container {
        max-width: 90%;
    }
</style>

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, comment = "", message = FALSE, warning = FALSE)
Sys.setlocale(category='LC_ALL','en_US.UTF-8')
options(shiny.sanitize.errors = FALSE, scipen = 999) # large numbers should be in full display
sys_user <- Sys.info()["user"]

```

```{r helper-functions, include=FALSE}

table <- function(..., useNA = 'ifany') base::table(..., useNA = useNA)

```


```{r import-data, include=FALSE}

## -----------------------------------------------------------------------------
## load packages

pkgs <- c("readr", "tidyr", "dplyr", "shiny", "xlsx", "RTA")
sapply(pkgs, require, character.only = TRUE)

switch(
    sys_user,
    dieulinh = {library("DT")},
    {library("DT", lib.loc = "/home/haoly/R/library/DT-1.0.0")}
)

## -----------------------------------------------------------------------------
## import data

switch(
    sys_user,
    dieulinh = {
      data_dir <- "/home/dieulinh/MEGAsync/RTA/KINGSMEN/data/"
      asm_target_sr <- read_csv(paste0(data_dir, "ASM_TARGET_SALEREP_TEST/ASM_TARGET_SALEREP_TEST.csv"), col_types= cols(.default = "c"))
      asm_rr <- read_csv(paste0(data_dir, "ASM_TARGET_SALEREP_TEST/asm_rr.csv"), col_types= cols(.default = "c"))
      asm_rrr <- read_csv(paste0(data_dir, "ASM_TARGET_SALEREP_TEST/asm_rrr.csv"), col_types= cols(.default = "c"))
      asm_rr1 <- read_csv(paste0(data_dir, "ASM_TARGET_SALEREP_TEST/asm_rr1.csv"), col_types= cols(.default = "c"))
      msr_sales <- read_csv(paste0(data_dir, "MSR_SALES_DEMO/MSR_SALES_DEMO.csv"), col_types= cols(.default = "c"))
      msr_sales_rr <- read_csv(paste0(data_dir, "MSR_SALES_DEMO/sales_rr.csv"), col_types= cols(.default = "c"))
      msr_remote <- read_csv(paste0(data_dir, "MSR_SALES_REMOTE_DEMO/MSR_SALES_REMOTE_DEMO.csv"), col_types= cols(.default = "c"))
      msr_remote_rr <- read_csv(paste0(data_dir, "MSR_SALES_REMOTE_DEMO/sales_rr.csv"), col_types= cols(.default = "c"))
     # msr_checkin <- read_csv(paste0(data_dir, "MSR_CHECKIN_DEMO/MSR_CHECKIN_DEMO.csv"), col_types= cols(.default = "c"))

    }, {
      asm_target_sr <- get_family_data("C011", "ASM_TARGET_SALEREP_TEST")
      asm_rr <- get_family_data("C011", "ASM_TARGET_SALEREP_TEST", "asm_rr")
      asm_rrr <- get_family_data("C011", "ASM_TARGET_SALEREP_TEST", "asm_rrr")
      asm_rr1 <- get_family_data("C011", "ASM_TARGET_SALEREP_TEST", "asm_rr1")
      msr_sales <- get_family_data("C011", "MSR_SALES_DEMO")
      msr_sales_rr <- get_family_data("C011", "MSR_SALES_DEMO", "sales_rr")
      msr_remote <- get_family_data("C011", "MSR_SALES_REMOTE_DEMO")
      msr_remote_rr <- get_family_data("C011", "MSR_SALES_REMOTE_DEMO", "sales_rr")
     # msr_checkin <- get_family_data("C011", "MSR_CHECKIN_DEMO")
      
    }
)

asm_target <- get_dm_data("C011", "ASM_target")
msr_staff <- get_dm_data("C011", "MSR_staff")
msr_product <- get_dm_data("C011", "MSR_product")

#colname_out <- c("SD", "RSM", "ASM", "Mã Sales Rep", "Tên Sales Rep", "Tổng doanh số - Chỉ tiêu", "Tổng doanh số - Đạt được", "Tổng doanh số - %Đạt được", "Bao phủ NT - Chỉ tiêu", "Bao phủ NT - Đạt được","Bao phủ NT - %Đạt được", "Mở mới NT - Chỉ tiêu", "Mở mới NT - Đạt được", "Mở mới NT - %Đạt được")

colname_out <- c("SD", "RSM", "ASM", "Mã Sales Rep", "Tên Sales Rep", "Tổng doanh số - Chỉ tiêu", "Tổng doanh số - Đạt được", "Tổng doanh số - %Đạt được", "Bao phủ NT - Đạt được", "Mở mới NT - Đạt được")
```


```{r prepare-data, include=FALSE}

asm_target_sr <- replace_with_na(asm_target_sr)
asm_rr <- replace_with_na(asm_rr)
asm_rrr <- replace_with_na(asm_rrr)
asm_rr1 <- replace_with_na(asm_rr1)

msr_sales <- replace_with_na(msr_sales)
msr_sales_rr <- replace_with_na(msr_sales_rr)

msr_remote <- replace_with_na(msr_remote)
msr_remote_rr <- replace_with_na(msr_remote_rr)
#msr_checkin <- replace_with_na(msr_checkin)

### remove rta
msr_staff[] <- lapply(msr_staff, as.character)
msr_staff <- msr_staff[grepl("^DGW", msr_staff$staff_id),]
asm_target[] <- lapply(asm_target, as.character)


```



```{r compute-revenue, include=FALSE}

## -----------------------------------------------------------------------------
## raw data target
###Join raw and repeat data

msr_sales_rr <- left_join(msr_sales_rr, msr_sales, by = "instanceID")

msr_remote_rr <- left_join(msr_remote_rr, msr_remote, by = "instanceID")

msr_sales_remote <- bind_rows(msr_sales_rr, msr_remote_rr)

asm_rrr <- left_join(asm_rrr, asm_rr, by = c("X_PARENT_AURI" = "X_URI", "instanceID"))

asm_rr <- left_join(asm_rrr, asm_target_sr, by = "instanceID")

asm_rr <- left_join(asm_rr, 
                    asm_target[, c("target_id", "month", "product_id")],
                    by = c("target_month" = "target_id",
                           "product_id"))

asm_rr <- left_join(asm_rr,
                    msr_product[, c("product_id", "product_price")],
                    by = "product_id")


## remove rta
#asm_rr <- asm_rr[grepl("^DGW", asm_rr$staff_id),]

##Create period

asm_rr$submission_date <- lubridate::ymd_hms(asm_rr$submission_date)

msr_sales_remote$sales_date <- lubridate::dmy(msr_sales_remote$sales_date)
msr_sales_remote$month <- format(msr_sales_remote$sales_date, "%m/%Y")

#msr_checkin$work_date <- lubridate::dmy(msr_checkin$work_date)
#msr_checkin$month <- format(msr_checkin$work_date, "%m/%Y")

##Filter latest data

asm_rr <- asm_rr %>% 
  group_by(month, staff_id) %>% 
  mutate(latest = submission_date == max(submission_date, na.rm = TRUE)) %>%
  ungroup()

asm_rr <- filter(asm_rr, latest == TRUE)
asm_rr$latest <- NULL

##Count checkin, newstore, coverstore

#count_checkin <- msr_checkin %>% 
#  group_by(month, staff_id) %>% 
#  summarize(real_checkin = n()) %>%
#  ungroup()

count_final <- msr_sales_remote %>% 
    group_by(month, staff_id) %>%
    summarize(real_newstore = n_distinct(new_store == 1),
              real_coverstore = n_distinct(store_id))

#count_final <- full_join(count_checkin, count_new_cover, by = c("month", "staff_id"))
 
##Calculate achivement money, percent 
asm_rr <- left_join(asm_rr, 
                    select(msr_sales_remote,
                           staff_id, product_id, month, product_total_money),
                    by = c("staff_id", "product_id", "month"))


col_character <- c("turnover", "product_price", "product_total_money")
asm_rr[,col_character] <- sapply((asm_rr[, col_character]), as.double)

asm_rr$target_money <- asm_rr$product_price * asm_rr$turnover

asm_rr <- asm_rr %>% 
  group_by(month, staff_id) %>% 
  summarize(target_money = sum(target_money, na.rm = T),
            real_money = sum(product_total_money, na.rm = T)) %>% 
  ungroup()
          
asm_rr <- left_join(asm_rr, 
                    count_final,
                    by = c("staff_id", "month"))

asm_rr <- left_join(asm_rr, 
                   msr_staff[, c("staff_id", "staff_lb", "staff_add", "supasm_id", "supasm_lb", 
                                 "suprsm_id", "suprsm_lb", "supsd_id", "supsd_lb",
                                 "region_id", "region_lb", "user_role")], by = "staff_id")


## filtering data by user role

role_mapping <- make_dict(msr_staff$username, msr_staff$user_role)
staff_dict <- make_dict(msr_staff$username, msr_staff$staff_id)

if (sys_user == "dieulinh") {
    user_name <- 'dgw_duhtrang'
    user_role <- 'ASM'
  	#user_name <- '$$FilterValue::get_user_info("##USERNAME##","username")$$'
    #user_role <- encode(user_name, role_mapping)
    user_id <- encode(user_name, staff_dict)

    if (user_role == "SR") {
        asm_rr <- filter(asm_rr, staff_id == user_id)
        msr_staff <- filter(msr_staff, staff_id == user_id)
    }

    if (user_role == "ASM") {
        asm_rr <- filter(asm_rr, supasm_id == user_id)
        msr_staff <- filter(msr_staff, supasm_id == user_id)
    }

    if (user_role == "RSM") {
        asm_rr <- filter(asm_rr, suprsm_id == user_id)
        msr_staff <- filter(msr_staff, suprsm_id == user_id)
    }

    if (user_role == "SD") {
        asm_rr <- filter(asm_rr, supsd_id == user_id)
        msr_staff <- filter(msr_staff, supsd_id == user_id)
    }
}

## -----------------------------------------------------------------------------
## inputs to input-panels

input_years <- 2017:(current_year()+1)
input_months <- 1:12
#input_dates <- unique(c(msr_sales_remote$sales_date, msr_checkin$work_date))
input_dates <- unique(msr_sales_remote$sales_date)

input_levels <- c("RSM", "ASM", "SR")


#level <- msr_staff %>% filter(staff_add != "RTA")

#level_out <- level %>% 
#  select(staff_lb, staff_id, user_role)

#sr_level <- level_out %>% filter(user_role == "SR") 
#input_SR <- c("Tất cả" = "All", make_dict(sr_level$staff_lb, sr_level$staff_id))

#asm_level <- level_out %>% filter(user_role == "ASM") 
#input_ASM <- c("Tất cả" = "All", make_dict(asm_level$staff_lb, asm_level$staff_id))

#rsm_level <- level_out %>% filter(user_role == "RSM") 
#input_RSM <- c("Tất cả" = "All", make_dict(rsm_level$staff_lb, rsm_level$staff_id))

input_SD <- distinct(select(msr_staff, supsd_id, supsd_lb))
input_SD <- filter(input_SD, supsd_id != "", !is.na(supsd_id))
input_SD <- c("Tất cả" = "All", make_dict(input_SD$supsd_lb, input_SD$supsd_id))

input_RSM <- distinct(select(msr_staff, suprsm_id, suprsm_lb))
input_RSM <- filter(input_RSM, suprsm_id != "", !is.na(suprsm_id))
input_RSM <- c("Tất cả" = "All", make_dict(input_RSM$suprsm_lb, input_RSM$suprsm_id))

input_ASM <- distinct(select(msr_staff, supasm_id, supasm_lb))
input_ASM <- filter(input_ASM, supasm_id != "", !is.na(supasm_id))
input_ASM <- c("Tất cả" = "All", make_dict(input_ASM$supasm_lb, input_ASM$supasm_id))

input_SR <- distinct(select(msr_staff, staff_id, staff_lb))
input_SR <- filter(input_SR, staff_id != "", !is.na(staff_id))
input_SR <- c("Tất cả" = "All", make_dict(input_SR$staff_lb, input_SR$staff_id))

```


```{r server-processing, include=FALSE}

re_target <- reactive({
  month_ip <- paste0(input$month_ip, "/", input$year_ip)
  out <- filter(asm_rr, month %in% month_ip)
  #out <- filter(out, user_role %in% input$level_ip)
  
  
  if(input$level_ip == "SR"){
    out <- out
    
    if(input$SR_input != "All"){
      out <- out %>% filter(staff_id %in% input$SR_input) 
    }
  }
  
  if(input$level_ip == "ASM"){
    out <- out
    if(input$ASM_input != "All"){
      out <- out %>% filter(supasm_id %in% input$ASM_input) 
    }
  }
  
  if(input$level_ip == "RSM"){
    out <- out
    if(input$RSM_input != "All"){
      out <- out %>% filter(suprsm_id %in% input$RSM_input) 
    }
  }
  
  
  validate(
    need(nrow(out) > 0, "Không có dữ liệu trong khoảng thời gian này")
  )
  

  out2 <- out %>%
  group_by(supsd_lb, suprsm_lb, supasm_lb) %>%
  summarise_at(c("target_money", "real_money",
                 "real_newstore",
                 "real_coverstore"), sum, na.rm = T) %>%
  mutate(supasm_lb = paste(supasm_lb, "Total", sep = " ")) %>%
  bind_rows(out) %>%
  arrange(supsd_lb, suprsm_lb, supasm_lb)

  out3 <- out %>%
  group_by(supsd_lb, suprsm_lb) %>%
  summarise_at(c("target_money", "real_money",
                 "real_newstore",
                 "real_coverstore"), sum, na.rm = T) %>%
  mutate(suprsm_lb = paste(suprsm_lb, "Total")) %>%
  bind_rows(out2) %>%
  arrange(supsd_lb, suprsm_lb) 

  out4 <- out %>%
  group_by(supsd_lb) %>%
  summarise_at(c("target_money", "real_money",
                 "real_newstore",
                 "real_coverstore"), sum, na.rm = T) %>%
  mutate(supsd_lb = paste(supsd_lb, "Total")) %>%
  bind_rows(out3) %>%
  arrange(supsd_lb) %>%
  mutate_all(funs(replace(., is.na(.), ""))) %>%
  mutate_at(c("supsd_lb", "suprsm_lb"), funs(ifelse(grepl("Total", supasm_lb), "", .))) %>%
  mutate(supsd_lb = ifelse(grepl("Total", suprsm_lb), "", supsd_lb)) %>%
  select(colnames(out))

col_char <- c("target_money", "real_money")
out4[,col_char] <- sapply((out4[, col_char]), as.double)

 out4$per_money <- round(out4$real_money * 100/ out4$target_money, 2)
 
  
 out4 <- out4[, c("supsd_lb", "suprsm_lb", "supasm_lb", "staff_id", "staff_lb", 
                "target_money", "real_money", "per_money",
                "real_newstore", "real_coverstore")]

   

names(out4) <- colname_out
out4
})


output$target_tbl <- DT::renderDataTable(
{re_target()},
class = "nowrap stripe hover cell-border",
rownames = FALSE,
filter = "top",
options = list(scrollX = TRUE,
               ordering = FALSE,
               pageLength = 20,
               language = list(url = "//cdn.datatables.net/plug-ins/1.10.7/i18n/Vietnamese.json"))
)

output$target_xls <- downloadHandler(
    filename = paste0("TARGET_SALESREP_", format(Sys.time(), "%d%m%Y_%H%M%S"), ".xlsx"),
    content = function(file) {
        ## make workbook
        wb <- create_excel_file(re_target(),
                                sheet_name = "target",
                                sheet_title = c("Target"))
        ## save workbook to a file
        saveWorkbook(wb, file)
    }
)

```

Inputs {.sidebar}
-------------------------------------

```{r input-panel}


fluidRow(
    column(
        width = 12,
        selectInput(
              inputId = "year_ip",
              label = tags$strong("Chọn năm:"),
              choices = input_years,
              selected = current_year())
    )
)


fluidRow(
    column(
        width = 12,
        selectInput(
              inputId ="month_ip",
              label = tags$strong("Chọn tháng:"),
              choices = input_months,
              selected = current_month())
    )
)

tags$br()


fluidRow(
  column(
    width = 12,
    radioButtons(
               inputId ="level_ip",
               label = tags$strong("Chọn cấp bậc:"),
               choices = input_levels, 
               selected = "SR")
  )
)

fluidRow(
  column(
    width = 12,
    conditionalPanel(
      condition = "input.level_ip =='SR'",
      selectInput(
                inputId ="SR_input",
                label ="Chọn SalesRep: ",
                choice = input_SR)
      ),
    
    conditionalPanel(
      condition = "input.level_ip =='ASM'",
      selectInput(
                inputId ="ASM_input",
                label ="Chọn ASM: ",
                choice = input_ASM)),
    
    conditionalPanel(
      condition = "input.level_ip =='RSM'",
      selectInput(
                inputId ="RSM_input",
                label ="Chọn RSM: ",
                choice = input_RSM))
      
    )
  )

tags$br()
```




Column
-------------------------------------

### **Bảng tổng hợp**
```{r}

fluidRow(
    column(
        width = 12,
        DT::dataTableOutput(outputId = "target_tbl")
    )
)

fluidRow(
    column(
        width = 2,
        downloadButton(outputId = "target_xls", label = "xlsx")
    )
)

```


